services:
  overlol:
    build: .
    ports:
      - '3000:3000'
    volumes:
      # Persist overlay storage data
      - overlay-data:/app/.overlay-storage
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  overlay-data:
    driver: local
